spring:
  application:
    name: demo
  main:
    web-application-type: "none"
logging:
  level:
    root: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver: DEBUG